In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Importing all the required datasets
members_df = pd.read_csv("C:\\Users\\User\\OneDrive\\DISCOVERY_INSURANCE_PROJECT\\members_dirty.csv")
claims_df = pd.read_csv("C:\\Users\\User\\OneDrive\\DISCOVERY_INSURANCE_PROJECT\\claims_dirty.csv")
vitality_df = pd.read_csv("C:\\Users\\User\\OneDrive\\DISCOVERY_INSURANCE_PROJECT\\vitality_dirty.csv")

In [5]:
#display the dataframes
members_df.head(20)

,member_id,name,age,gender,plan_type,chronic_condition,region,join_date
0,M00001,Scott Lewis,56,Male,Essential,0,western cape,2022-09-12
1,M00002,Krystal Fritz,69,Female,KeyCare,1,eastern cape,2021-01-30
2,M00003,Michael Morrison,46,Male,KeyCare,0,kzn,2019-08-15
3,M00004,Jose Johnson,32,Female,Essential,0,Eastern Cape,2019-02-17
4,M00005,Sierra Conner,60,Male,Essential,0,K.Z.N,2021-11-07
5,M00006,Michelle Brown,25,Male,Classic,0,KZN,2021-06-30
6,M00007,George Roberts,38,Female,KeyCare,1,gauteng,2023-01-02
7,M00008,Philip Clements,56,Male,Classic,0,Gauten,2023-09-28
8,M00009,Becky Rosales,36,Male,KeyCare,1,Eastern Cape,2019-07-06
9,M00010,Gabriel Oconnell,40,Male,Essential,1,Gauten,2019-12-11
10,M00011,Angela Wallace,28,Male,Essential,0,Gauten,2019-08-12
11,M00012,Timothy Kemp,28,Male,Essential,0,Gauten,2021-04-09
12,M00013,James Smith,41,Male,Classic,0,E.Cape,2020-05-02
13,M00014,Richard Valencia,70,Female,Classic,1,Western Cape,2021-05-26
14,M00015,Kathleen Evans,53,Male,Classic,0,gauteng,2021-04-28
15,M00016,Patricia Williams,57,Male,Classic,0,Gauteng,2022-06-06
16,M00017,Stephen Hines,41,Female,Essential,1,eastern cape,2022-11-14
17,M00018,James Stokes,20,Female,Classic,0,western cape,2021-09-05
18,M00019,Charles Peterson,39,Female,Classic,1,NaN,2023-06-01
19,M00020,Jennifer Gonzalez,70,Female,KeyCare,0,KZN,2021-10-13

In [7]:
#display the dataframes
claims_df.head(10)

,claim_id,member_id,claim_date,provider_type,diagnosis_code,amount_claimed,amount_paid
0,C000001,M00556,2021-10-06,GP,D003,"1,222.34",863.27
1,C000002,M00610,2022-04-24,Specialist,D002,730.29,527.49
2,C000003,M00773,2021-04-21,Pharmacy,D004,651.62,612.04
3,C000004,M00109,2022-03-07,Pharmacy,D002,"1,192.13",884.53
4,C000005,M00795,2022-06-26,GP,D002,"1,337.34",1216.64
5,C000006,M00372,2021-12-26,Pharmacy,D005,"1,113.16",1015.94
6,C000007,M00855,2022-01-07,GP,D002,971.63,970.53
7,C000008,M00616,2023-11-05,GP,D002,"1,099.75",999.32
8,C000009,M00768,2023-08-13,Specialist,D002,"1,174.53",867.54
9,C000010,M00891,2021-09-16,Specialist,D001,"1,198.66",1064.37

In [9]:
#display the dataframes
vitality_df.head(10)

  member_id  week_start    steps  gym_visits  points_earned
0    M00049  2022-10-10   5511.0           4          134.0
1    M00978  2022-10-17   8708.0           4          142.0
2    M00577  2022-03-14   3119.0           0            1.0
3    M00701  2023-10-09  11327.0           2            9.0
4    M00521  2022-10-24   8034.0           3          138.0
5    M00394  2023-08-21  15358.0           2           52.0
6    M00880  2022-02-21   5765.0           1           55.0
7    M00395  2022-11-14   8397.0           2           39.0
8    M00096  2022-08-22  15830.0           1           75.0
9    M00085  2023-10-23  12071.0           0           91.0

# CLEANING DATA

#Checking all null values in all dataframes

In [13]:
#1. Check null values sum of null values in each column.
members_df.isna().sum()

member_id             0
name                  0
age                   0
gender               50
plan_type             0
chronic_condition     0
region               30
join_date             0
dtype: int64

In [15]:
#In the members dataframe we find that we are only finding null values in the two data column; gender and region
#By the finding the best way to elliminate null variables of the data to ensure cean and accurate insight we can 
#In this instance we will fill null values to 'unknown' for both columns(genders, and region)
members_df["gender"] = members_df["gender"].fillna("Uknown")
members_df["region"] = members_df["region"].fillna("Unkown")

members_df.isna().sum()

member_id            0
name                 0
age                  0
gender               0
plan_type            0
chronic_condition    0
region               0
join_date            0
dtype: int64

In [17]:
members_df.head()

,member_id,name,age,gender,plan_type,chronic_condition,region,join_date
0,M00001,Scott Lewis,56,Male,Essential,0,western cape,2022-09-12
1,M00002,Krystal Fritz,69,Female,KeyCare,1,eastern cape,2021-01-30
2,M00003,Michael Morrison,46,Male,KeyCare,0,kzn,2019-08-15
3,M00004,Jose Johnson,32,Female,Essential,0,Eastern Cape,2019-02-17
4,M00005,Sierra Conner,60,Male,Essential,0,K.Z.N,2021-11-07

#claim_data set null value check

In [20]:
#claim data null check andsum
claims_df.isna().sum()

claim_id            0
member_id           0
claim_date          0
provider_type       0
diagnosis_code    100
amount_claimed      0
amount_paid        50
dtype: int64

In [22]:
#we find null values in 'diagnosis_code' 
claims_df['diagnosis_code'] = claims_df['diagnosis_code'].fillna("Uknown")
claims_df.isna().sum()

claim_id           0
member_id          0
claim_date         0
provider_type      0
diagnosis_code     0
amount_claimed     0
amount_paid       50
dtype: int64

In [24]:
#Currently the amounts paid and amount claimed are in string data type - need to convert to numeric
claims_df['amount_paid'] = pd.to_numeric(claims_df['amount_paid'].replace(',','',regex=True))
claims_df['amount_claimed'] = pd.to_numeric(claims_df['amount_claimed'].replace(',','',regex=True))


#we find null values and 'amounts_paid' - filling with unknown is the best way to keep data integrity

claims_df.head(5)

,claim_id,member_id,claim_date,provider_type,diagnosis_code,amount_claimed,amount_paid
0,C000001,M00556,2021-10-06,GP,D003,1222.34,863.27
1,C000002,M00610,2022-04-24,Specialist,D002,730.29,527.49
2,C000003,M00773,2021-04-21,Pharmacy,D004,651.62,612.04
3,C000004,M00109,2022-03-07,Pharmacy,D002,1192.13,884.53
4,C000005,M00795,2022-06-26,GP,D002,1337.34,1216.64

In [26]:
#we find null values and 'amounts_paid' - filling with unknown is the best way to keep data integrity

claims_df['amount_paid'] = claims_df['amount_paid'].fillna(claims_df['amount_paid'].mean())
claims_df.isna().sum()

claim_id          0
member_id         0
claim_date        0
provider_type     0
diagnosis_code    0
amount_claimed    0
amount_paid       0
dtype: int64

In [28]:
claims_df.head(10)

,claim_id,member_id,claim_date,provider_type,diagnosis_code,amount_claimed,amount_paid
0,C000001,M00556,2021-10-06,GP,D003,1222.34,863.27
1,C000002,M00610,2022-04-24,Specialist,D002,730.29,527.49
2,C000003,M00773,2021-04-21,Pharmacy,D004,651.62,612.04
3,C000004,M00109,2022-03-07,Pharmacy,D002,1192.13,884.53
4,C000005,M00795,2022-06-26,GP,D002,1337.34,1216.64
5,C000006,M00372,2021-12-26,Pharmacy,D005,1113.16,1015.94
6,C000007,M00855,2022-01-07,GP,D002,971.63,970.53
7,C000008,M00616,2023-11-05,GP,D002,1099.75,999.32
8,C000009,M00768,2023-08-13,Specialist,D002,1174.53,867.54
9,C000010,M00891,2021-09-16,Specialist,D001,1198.66,1064.37

#checking null values in Vitality data table

In [31]:
#checkung sum of null values in each columns
vitality_df.isna().sum()

member_id         0
week_start        0
steps            60
gym_visits        0
points_earned    40
dtype: int64

In [33]:
#we find them in 'steps', and 'points_earned'
#since we are working with sumabe data now - the best thong to fill null values is to place the mean value in the missing value placements
#first check the mean
round(vitality_df["steps"].mean(), 0)#how do i round up to 0 decimal places

11174.0

In [35]:
#Now i am filling missing values with null values in the steps column
vitality_df["steps"] = vitality_df["steps"].fillna(round(vitality_df["steps"].mean(),0))#rounding up to a whole number
#filling the points earned - with this column i will fill using the median operation
vitality_df["points_earned"] = vitality_df["points_earned"].fillna(round(vitality_df["points_earned"].median(),0))
vitality_df.isna().sum()

member_id        0
week_start       0
steps            0
gym_visits       0
points_earned    0
dtype: int64

# DataType cleaning

In [38]:
members_df.select_dtypes(include='object').columns

Index(['member_id', 'name', 'gender', 'plan_type', 'region', 'join_date'], dtype='object')

In [40]:
#to turn the data column to str, this will change the type from object(errors) to string values
members_df['member_id'] = members_df['member_id'].astype(str)

#Changing to categorical type on these column
members_df['gender'] = members_df['gender'].astype('category')
members_df['plan_type'] = members_df['plan_type'].astype('category')
members_df['region'] = members_df['region'].astype('category')

#converting join_date data to be a datetime data type
members_df['join_date'] = pd.to_datetime(members_df['join_date'], errors='coerce')

In [42]:
members_df.dtypes

member_id                    object
name                         object
age                           int64
gender                     category
plan_type                  category
chronic_condition             int64
region                     category
join_date            datetime64[ns]
dtype: object

In [44]:
#SPLITTING THE NAME COLUMN TO TWO seperate first  name and surname - 
#for better data visulaition in the following stages
members_df[["FirstName","Surname"]] = members_df["name"].str.strip().str.split(' ',n=1, expand=True)

members_df.head()

,member_id,name,age,gender,plan_type,chronic_condition,region,join_date,FirstName,Surname
0,M00001,Scott Lewis,56,Male,Essential,0,western cape,2022-09-12,Scott,Lewis
1,M00002,Krystal Fritz,69,Female,KeyCare,1,eastern cape,2021-01-30,Krystal,Fritz
2,M00003,Michael Morrison,46,Male,KeyCare,0,kzn,2019-08-15,Michael,Morrison
3,M00004,Jose Johnson,32,Female,Essential,0,Eastern Cape,2019-02-17,Jose,Johnson
4,M00005,Sierra Conner,60,Male,Essential,0,K.Z.N,2021-11-07,Sierra,Conner

In [46]:
#dropping the name column
members_df.drop("name", axis=1, inplace=True)

##Restructuring the data columns
members_df = members_df[["member_id","FirstName", "Surname","age","gender","plan_type",
                         "chronic_condition","region","join_date"]]
members_df.head(10)

,member_id,FirstName,Surname,age,gender,plan_type,chronic_condition,region,join_date
0,M00001,Scott,Lewis,56,Male,Essential,0,western cape,2022-09-12
1,M00002,Krystal,Fritz,69,Female,KeyCare,1,eastern cape,2021-01-30
2,M00003,Michael,Morrison,46,Male,KeyCare,0,kzn,2019-08-15
3,M00004,Jose,Johnson,32,Female,Essential,0,Eastern Cape,2019-02-17
4,M00005,Sierra,Conner,60,Male,Essential,0,K.Z.N,2021-11-07
5,M00006,Michelle,Brown,25,Male,Classic,0,KZN,2021-06-30
6,M00007,George,Roberts,38,Female,KeyCare,1,gauteng,2023-01-02
7,M00008,Philip,Clements,56,Male,Classic,0,Gauten,2023-09-28
8,M00009,Becky,Rosales,36,Male,KeyCare,1,Eastern Cape,2019-07-06
9,M00010,Gabriel,Oconnell,40,Male,Essential,1,Gauten,2019-12-11

In [48]:
#standardization of variations
members_df['region'] = members_df['region'].str.replace('.','', regex=False).str.upper().str.strip()
members_df.head(25)

,member_id,FirstName,Surname,age,gender,plan_type,chronic_condition,region,join_date
0,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12
1,M00002,Krystal,Fritz,69,Female,KeyCare,1,EASTERN CAPE,2021-01-30
2,M00003,Michael,Morrison,46,Male,KeyCare,0,KZN,2019-08-15
3,M00004,Jose,Johnson,32,Female,Essential,0,EASTERN CAPE,2019-02-17
4,M00005,Sierra,Conner,60,Male,Essential,0,KZN,2021-11-07
5,M00006,Michelle,Brown,25,Male,Classic,0,KZN,2021-06-30
6,M00007,George,Roberts,38,Female,KeyCare,1,GAUTENG,2023-01-02
7,M00008,Philip,Clements,56,Male,Classic,0,GAUTEN,2023-09-28
8,M00009,Becky,Rosales,36,Male,KeyCare,1,EASTERN CAPE,2019-07-06
9,M00010,Gabriel,Oconnell,40,Male,Essential,1,GAUTEN,2019-12-11
10,M00011,Angela,Wallace,28,Male,Essential,0,GAUTEN,2019-08-12
11,M00012,Timothy,Kemp,28,Male,Essential,0,GAUTEN,2021-04-09
12,M00013,James,Smith,41,Male,Classic,0,ECAPE,2020-05-02
13,M00014,Richard,Valencia,70,Female,Classic,1,WESTERN CAPE,2021-05-26
14,M00015,Kathleen,Evans,53,Male,Classic,0,GAUTENG,2021-04-28
15,M00016,Patricia,Williams,57,Male,Classic,0,GAUTENG,2022-06-06
16,M00017,Stephen,Hines,41,Female,Essential,1,EASTERN CAPE,2022-11-14
17,M00018,James,Stokes,20,Female,Classic,0,WESTERN CAPE,2021-09-05
18,M00019,Charles,Peterson,39,Female,Classic,1,UNKOWN,2023-06-01
19,M00020,Jennifer,Gonzalez,70,Female,KeyCare,0,KZN,2021-10-13
20,M00021,Jennifer,Martinez,19,Female,KeyCare,0,ECAPE,2019-07-07
21,M00022,Michael,Harper,41,Female,KeyCare,0,GAUTENG,2019-09-27
22,M00023,Robert,Cox,61,Female,KeyCare,1,GAUTENG,2023-06-19
23,M00024,Kevin,Sampson,47,Male,Classic,0,KZN,2019-11-06
24,M00025,Gregory,Ruiz,55,Male,Classic,1,KZN,2022-03-01

In [50]:
region_map={
    'ECAPE':'EASTERN CAPE',
}
members_df['region'] = members_df['region'].replace(region_map)
members_df.head(25)

,member_id,FirstName,Surname,age,gender,plan_type,chronic_condition,region,join_date
0,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12
1,M00002,Krystal,Fritz,69,Female,KeyCare,1,EASTERN CAPE,2021-01-30
2,M00003,Michael,Morrison,46,Male,KeyCare,0,KZN,2019-08-15
3,M00004,Jose,Johnson,32,Female,Essential,0,EASTERN CAPE,2019-02-17
4,M00005,Sierra,Conner,60,Male,Essential,0,KZN,2021-11-07
5,M00006,Michelle,Brown,25,Male,Classic,0,KZN,2021-06-30
6,M00007,George,Roberts,38,Female,KeyCare,1,GAUTENG,2023-01-02
7,M00008,Philip,Clements,56,Male,Classic,0,GAUTEN,2023-09-28
8,M00009,Becky,Rosales,36,Male,KeyCare,1,EASTERN CAPE,2019-07-06
9,M00010,Gabriel,Oconnell,40,Male,Essential,1,GAUTEN,2019-12-11
10,M00011,Angela,Wallace,28,Male,Essential,0,GAUTEN,2019-08-12
11,M00012,Timothy,Kemp,28,Male,Essential,0,GAUTEN,2021-04-09
12,M00013,James,Smith,41,Male,Classic,0,EASTERN CAPE,2020-05-02
13,M00014,Richard,Valencia,70,Female,Classic,1,WESTERN CAPE,2021-05-26
14,M00015,Kathleen,Evans,53,Male,Classic,0,GAUTENG,2021-04-28
15,M00016,Patricia,Williams,57,Male,Classic,0,GAUTENG,2022-06-06
16,M00017,Stephen,Hines,41,Female,Essential,1,EASTERN CAPE,2022-11-14
17,M00018,James,Stokes,20,Female,Classic,0,WESTERN CAPE,2021-09-05
18,M00019,Charles,Peterson,39,Female,Classic,1,UNKOWN,2023-06-01
19,M00020,Jennifer,Gonzalez,70,Female,KeyCare,0,KZN,2021-10-13
20,M00021,Jennifer,Martinez,19,Female,KeyCare,0,EASTERN CAPE,2019-07-07
21,M00022,Michael,Harper,41,Female,KeyCare,0,GAUTENG,2019-09-27
22,M00023,Robert,Cox,61,Female,KeyCare,1,GAUTENG,2023-06-19
23,M00024,Kevin,Sampson,47,Male,Classic,0,KZN,2019-11-06
24,M00025,Gregory,Ruiz,55,Male,Classic,1,KZN,2022-03-01

# CLAIMS DATA - DATA TYPES

In [53]:
claims_df.dtypes

claim_id           object
member_id          object
claim_date         object
provider_type      object
diagnosis_code     object
amount_claimed    float64
amount_paid       float64
dtype: object

In [55]:
#converting to strings
claims_df["claim_id"] = claims_df["claim_id"].astype(str)
claims_df["member_id"] = claims_df["member_id"].astype(str)

#converting to category
claims_df["provider_type"] = claims_df["provider_type"].astype("category")
claims_df["diagnosis_code"] = claims_df["diagnosis_code"].astype("category")

#converting to claim_date to datetime
claims_df['claim_date'] = pd.to_datetime(claims_df['claim_date'], errors='coerce')

claims_df.dtypes

claim_id                  object
member_id                 object
claim_date        datetime64[ns]
provider_type           category
diagnosis_code          category
amount_claimed           float64
amount_paid              float64
dtype: object

# Vitality data frame data type standardizing

In [58]:
vitality_df.dtypes

member_id         object
week_start        object
steps            float64
gym_visits         int64
points_earned    float64
dtype: object

In [60]:
vitality_df.head()

  member_id  week_start    steps  gym_visits  points_earned
0    M00049  2022-10-10   5511.0           4          134.0
1    M00978  2022-10-17   8708.0           4          142.0
2    M00577  2022-03-14   3119.0           0            1.0
3    M00701  2023-10-09  11327.0           2            9.0
4    M00521  2022-10-24   8034.0           3          138.0

In [62]:
#converting to week_start to datetime
vitality_df['week_start'] = pd.to_datetime(vitality_df['week_start'], errors='coerce')

In [64]:
vitality_df.dtypes

member_id                object
week_start       datetime64[ns]
steps                   float64
gym_visits                int64
points_earned           float64
dtype: object

# MERGE DATASETS

In [67]:
#STEP 1: MERGE MEMBER_DF AND CLAIMS_DF
merge1 = pd.merge(members_df, claims_df, on="member_id",how ="left")
merge1.head()

,member_id,FirstName,Surname,age,gender,plan_type,chronic_condition,region,join_date,claim_id,claim_date,provider_type,diagnosis_code,amount_claimed,amount_paid
0,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C000489,2023-02-12,GP,D005,1168.88,1116.520000
1,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C000731,2022-01-11,Specialist,D003,1782.10,1016.963384
2,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C000993,2023-09-11,Specialist,D002,1143.94,938.430000
3,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C001067,2021-01-26,Specialist,D003,2028.59,1582.320000
4,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C001413,2022-12-29,Specialist,D003,848.12,777.150000

In [69]:
#final merged data(merge1, and vitality)
MemberVitality_df = pd.merge(merge1, vitality_df, on ="member_id", how="left")
MemberVitality_df.head(5)

,member_id,FirstName,Surname,age,gender,plan_type,chronic_condition,region,join_date,claim_id,claim_date,provider_type,diagnosis_code,amount_claimed,amount_paid,week_start,steps,gym_visits,points_earned
0,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C000489,2023-02-12,GP,D005,1168.88,1116.520000,2023-07-31,10748.0,3.0,39.0
1,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C000731,2022-01-11,Specialist,D003,1782.10,1016.963384,2023-07-31,10748.0,3.0,39.0
2,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C000993,2023-09-11,Specialist,D002,1143.94,938.430000,2023-07-31,10748.0,3.0,39.0
3,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C001067,2021-01-26,Specialist,D003,2028.59,1582.320000,2023-07-31,10748.0,3.0,39.0
4,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C001413,2022-12-29,Specialist,D003,848.12,777.150000,2023-07-31,10748.0,3.0,39.0

In [71]:
MemberVitality_df["amount_paid"] = round(MemberVitality_df["amount_paid"],0)

In [73]:
MemberVitality_df.head(5)

,member_id,FirstName,Surname,age,gender,plan_type,chronic_condition,region,join_date,claim_id,claim_date,provider_type,diagnosis_code,amount_claimed,amount_paid,week_start,steps,gym_visits,points_earned
0,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C000489,2023-02-12,GP,D005,1168.88,1117.0,2023-07-31,10748.0,3.0,39.0
1,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C000731,2022-01-11,Specialist,D003,1782.10,1017.0,2023-07-31,10748.0,3.0,39.0
2,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C000993,2023-09-11,Specialist,D002,1143.94,938.0,2023-07-31,10748.0,3.0,39.0
3,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C001067,2021-01-26,Specialist,D003,2028.59,1582.0,2023-07-31,10748.0,3.0,39.0
4,M00001,Scott,Lewis,56,Male,Essential,0,WESTERN CAPE,2022-09-12,C001413,2022-12-29,Specialist,D003,848.12,777.0,2023-07-31,10748.0,3.0,39.0

# TURN TO XLX OR CSV FILES
#CSV

In [98]:
NEW_DATA = MemberVitality_df.to_csv("MembersVitalityDATA.csv", index=False)

In [77]:
MemberVitality_df.to_excel("MembersVitality1.xlsx", index=False)

In [91]:
MemberVitality_df.isnull().sum()

member_id            0
FirstName            0
Surname              0
age                  0
gender               0
plan_type            0
chronic_condition    0
region               0
join_date            0
claim_id             0
claim_date           0
provider_type        0
diagnosis_code       0
amount_claimed       0
amount_paid          0
week_start           0
steps                0
gym_visits           0
points_earned        0
dtype: int64

In [80]:
MemberVitality_df["steps"] = MemberVitality_df["steps"].fillna(round(MemberVitality_df["steps"].mean(),0))

In [81]:
# Step 2: Fill NaN with the column's mean value (rounded if needed)
mean_visits = round(MemberVitality_df["gym_visits"].mean(), 0)
MemberVitality_df["gym_visits"] = MemberVitality_df["gym_visits"].fillna(mean_visits)

In [82]:
# Get the first mode (most common value)
mode_week_start = MemberVitality_df["week_start"].mode().iloc[0]

# Fill missing values with the mode
MemberVitality_df["week_start"] = MemberVitality_df["week_start"].fillna(mode_week_start)

In [83]:
mean_points = round(MemberVitality_df["points_earned"].mean(), 0)
MemberVitality_df["points_earned"] = MemberVitality_df["points_earned"].fillna(mean_points)

In [84]:
MemberVitality_df.to_excel("MembersVitalityData.xlsx", index=False)